### ISSUE TITLE
Projection process

### ISSUE THREAD

**Issue by zhangyahu1** [chenchao15/2D_projection_matching#1]
Thanks for sharing your nice work!

However, I have a question about the projection process. I assume the point clouds are fisrtly normalized into [-1,1] or [-0.5, 0.5] in your method. Therefore, given normalized point clouds _M_, how do you project them on the 2D plane using camera parameters shown in equation 1? 

I would appreciate it if you coud give me some hints.

**Comment by chenchao15** [comment]
Thank you for your question. 
Our model generates a standardized point cloud M with the shape of [n, 3] from the world coordinate system. In the projection process, we first use the camera parameters to rotate the point cloud M to the camera coordinate system to obtain M '[n, 3], then take the x-axis and Y-axis of M' to obtain the two-dimensional projection point set P [n, 2], and finally scale the point set P to the image resolution, which is our projection process.

**Comment by zhangyahu1** [comment]
Thanks for your explanation.
1) So the generated M is located at the world coordinate system. However, the statement in the paper is that M is in an object centered coordinate system. Is there any transformation?
2) Is it right to scale the point set P (projections) to the mask resoultion of the object?

**Comment by chenchao15** [comment]
1. world coordinate system is the same as the object-centered coordinate system.
2. Scaling is just to visualize 2D points onto the silhouette. No scaling during training.

**Comment by zhangyahu1** [comment]
Thanks!

**Comment by caiyongqi** [comment]
> 

Hi, It also seems to be scaled to the mask resolution during the training phase.
https://github.com/chenchao15/2D_projection_matching/blob/66d6188fdb2070db92099c73108be3cdab2b94c5/2Dpm/models/models.py#L283
